### ISSUE TITLE
Error 999999 when using GeMS_RelationshipClasses1_Arc10.py

### ISSUE THREAD

**Issue by ethoms-usgs** [ethoms-usgs/GeMS_Tools#2]
Submitted by rbeard09 at https://github.com/usgs/GeMS_Tools/issues/38 and confirmed by me.

```
RelationshipClasses
adding relationship class CAF_DataSourceID
Failed script Relationship Classes...
Traceback (most recent call last):
  File "D:\Current\GitHub\gems-tools\Scripts\GeMS_RelationshipClasses_AGP2.py", line 68, in <module>
    arcpy.CreateRelationshipClass_management(r[0],r[1],r[2],r[3],r[4],r[5],r[6],r[7],r[8],r[9],r[10])
  File "c:\arcgis\pro\Resources\arcpy\arcpy\management.py", line 18565, in CreateRelationshipClass
    raise e
  File "c:\arcgis\pro\Resources\arcpy\arcpy\management.py", line 18562, in CreateRelationshipClass
    retval = convertArcObjectToPythonObject(gp.CreateRelationshipClass_management(*gp_fixargs((origin_table, destination_table, out_relationship_class, relationship_type, forward_label, backward_label, message_direction, cardinality, attributed, origin_primary_key, origin_foreign_key, destination_primary_key, destination_foreign_key), True)))
  File "c:\arcgis\pro\Resources\arcpy\arcpy\geoprocessing\_base.py", line 506, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError:  ERROR 999999: Something unexpected caused the tool to fail. Contact Esri Technical Support (http://esriurl.com/support) to Report a Bug, and refer to the error help for potential solutions or workarounds.
Failed to execute (CreateRelationshipClass).
 Failed to execute (RelationshipClasses).
```

**Comment by ethoms-usgs** [comment]
V2.0.1 fixes this problem. For whatever reason , when this tool was run in ArcMap using Python 2, it was possible to write new relationship classes to an empty feature dataset with an unknown spatial reference. This was throwing the error with arcpy 3. Even if it would be possible to organize all relationship classes into their own feature dataset for that purpose, I think that is probably not a best practice. The re-written tool now creates relationship classes in the feature dataset in which the feature class is found. The new version also looks through all feature class tables in the GDB, not just those defined in the code,  for controlled fields, eg Type, MapUnit, Confidence fields, DataSourceID, etc; and then makes a relationship class between those fields and the appropriate tables.
In light of the possibility of running these tool against PostGIS gdbs, I also tried to account for table and field names that are not in CamelCase, that is, in all lower case.
